version: '3.5'


services: 
  database: 
    image: 'postgres'
    environment: 
      POSTGRES_PASSWORD: password
    networks:
      examplenet:
          ipv4_address: 10.5.0.3

networks:
  examplenet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16